spring:
  application:
    name: client-user
  redis:
#    database: 2
    host: localhost
    port: 6379
#    jedis:
#      pool:
#        max-active: 8
#        max-idle: 8
#        min-idle: 0
#    timeout: 100ms
server:
  port: 6101
  servlet:
    context-path: /client-user

security:
  oauth2:
    client:
      client-id: user-client #要和认证服务中的配置一致
      client-secret: user-secret-8888 #要和认证服务中的配置一致
      user-authorization-uri: http://localhost:6001/oauth/authorize #授权码认证方式需要
      access-token-uri: http://localhost:6001/oauth/token #密码模式需要用到的获取token的接口
    resource:
      id: user-client
      user-info-uri: user-info
    authorization:
      #当本服务接到来自客户端带有token的请求后，拿着请求中的token到下列的接口中做token验证
      check-token-access: http://localhost:6001/oauth/check_token